// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMcpServer(arg1, arg2) {
  return window['go']['main']['App']['AddMcpServer'](arg1, arg2);
}

export function AddSkillRepo(arg1) {
  return window['go']['main']['App']['AddSkillRepo'](arg1);
}

export function AutoAdoptSkills() {
  return window['go']['main']['App']['AutoAdoptSkills']();
}

export function CheckSkillUpdates() {
  return window['go']['main']['App']['CheckSkillUpdates']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CreateBackupNow(arg1) {
  return window['go']['main']['App']['CreateBackupNow'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteMcpServer(arg1) {
  return window['go']['main']['App']['DeleteMcpServer'](arg1);
}

export function ExportBackupToFile(arg1, arg2) {
  return window['go']['main']['App']['ExportBackupToFile'](arg1, arg2);
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetAgentMcpServers(arg1) {
  return window['go']['main']['App']['GetAgentMcpServers'](arg1);
}

export function GetBackup(arg1) {
  return window['go']['main']['App']['GetBackup'](arg1);
}

export function GetMarketServer(arg1, arg2) {
  return window['go']['main']['App']['GetMarketServer'](arg1, arg2);
}

export function GetMcpServer(arg1) {
  return window['go']['main']['App']['GetMcpServer'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkillRepos() {
  return window['go']['main']['App']['GetSkillRepos']();
}

export function GetStartupErrors() {
  return window['go']['main']['App']['GetStartupErrors']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportBackupFromFile(arg1, arg2) {
  return window['go']['main']['App']['ImportBackupFromFile'](arg1, arg2);
}

export function ImportSkillDirectory(arg1, arg2) {
  return window['go']['main']['App']['ImportSkillDirectory'](arg1, arg2);
}

export function InstallMarketServer(arg1, arg2) {
  return window['go']['main']['App']['InstallMarketServer'](arg1, arg2);
}

export function InstallMarketSkill(arg1, arg2) {
  return window['go']['main']['App']['InstallMarketSkill'](arg1, arg2);
}

export function InstallSkillFromZip(arg1, arg2) {
  return window['go']['main']['App']['InstallSkillFromZip'](arg1, arg2);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListMcpServers() {
  return window['go']['main']['App']['ListMcpServers']();
}

export function ListSkillCapableAgents() {
  return window['go']['main']['App']['ListSkillCapableAgents']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function MigrateSkillStorage(arg1) {
  return window['go']['main']['App']['MigrateSkillStorage'](arg1);
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFile(arg1) {
  return window['go']['main']['App']['PickFile'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveSkillRepo(arg1) {
  return window['go']['main']['App']['RemoveSkillRepo'](arg1);
}

export function RescanAgents() {
  return window['go']['main']['App']['RescanAgents']();
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function ResyncSkills() {
  return window['go']['main']['App']['ResyncSkills']();
}

export function ScanMcpServers() {
  return window['go']['main']['App']['ScanMcpServers']();
}

export function ScanUnmanagedSkills() {
  return window['go']['main']['App']['ScanUnmanagedSkills']();
}

export function SearchMarketServers(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchMarketServers'](arg1, arg2, arg3, arg4);
}

export function SearchMarketSkills(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchMarketSkills'](arg1, arg2, arg3, arg4);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleAgent(arg1, arg2) {
  return window['go']['main']['App']['ToggleAgent'](arg1, arg2);
}

export function ToggleMcpServerAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleMcpServerAgent'](arg1, arg2, arg3);
}

export function ToggleSkillAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleSkillAgent'](arg1, arg2, arg3);
}

export function UninstallSkill(arg1) {
  return window['go']['main']['App']['UninstallSkill'](arg1);
}

export function UpdateMcpServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateMcpServer'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSkillRepo(arg1, arg2) {
  return window['go']['main']['App']['UpdateSkillRepo'](arg1, arg2);
}
