// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';
import {config} from '../models';
import {skills} from '../models';
import {main} from '../models';
import {backup} from '../models';
import {agents} from '../models';
import {market} from '../models';

export function AddMcpServer(arg1:mcp.Server,arg2:Array<string>):Promise<void>;

export function AddSkillRepo(arg1:config.SkillRepo):Promise<void>;

export function AutoAdoptSkills():Promise<skills.AdoptionResult>;

export function CheckSkillUpdates():Promise<Array<skills.UpdateStatus>>;

export function CheckUpdate():Promise<main.UpdateCheckResult>;

export function CreateBackupNow(arg1:string):Promise<backup.Summary>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteMcpServer(arg1:string):Promise<void>;

export function ExportBackupToFile(arg1:string,arg2:string):Promise<string>;

export function GetAgent(arg1:string):Promise<agents.Agent>;

export function GetAgentMcpServers(arg1:string):Promise<Array<mcp.Server>>;

export function GetBackup(arg1:string):Promise<backup.Snapshot>;

export function GetMarketServer(arg1:string,arg2:string):Promise<market.MarketServer>;

export function GetMcpServer(arg1:string):Promise<mcp.Server>;

export function GetSettings():Promise<config.Settings>;

export function GetSkillRepos():Promise<Array<config.SkillRepo>>;

export function GetStartupErrors():Promise<Array<string>>;

export function HideWindow():Promise<void>;

export function ImportBackupFromFile(arg1:string,arg2:backup.ImportOptions):Promise<backup.ImportResult>;

export function ImportSkillDirectory(arg1:string,arg2:Array<string>):Promise<skills.Skill>;

export function InstallMarketServer(arg1:market.MarketServer,arg2:Array<string>):Promise<mcp.Server>;

export function InstallMarketSkill(arg1:market.MarketSkill,arg2:Array<string>):Promise<skills.Skill>;

export function InstallSkillFromZip(arg1:string,arg2:Array<string>):Promise<skills.Skill>;

export function ListAgents():Promise<Array<agents.Agent>>;

export function ListBackups():Promise<Array<backup.Summary>>;

export function ListMcpServers():Promise<Array<mcp.Server>>;

export function ListSkillCapableAgents():Promise<Array<agents.Agent>>;

export function ListSkills():Promise<Array<skills.Skill>>;

export function MigrateSkillStorage(arg1:string):Promise<skills.MigrationResult>;

export function OpenConfigFolder():Promise<void>;

export function PickDirectory():Promise<string>;

export function PickFile(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function RemoveSkillRepo(arg1:config.SkillRepo):Promise<void>;

export function RescanAgents():Promise<Array<agents.Agent>>;

export function RestoreBackup(arg1:string,arg2:backup.ImportOptions):Promise<backup.ImportResult>;

export function ResyncSkills():Promise<void>;

export function ScanMcpServers():Promise<mcp.ScanResult>;

export function ScanUnmanagedSkills():Promise<Array<skills.UnmanagedSkill>>;

export function SearchMarketServers(arg1:string,arg2:string,arg3:string,arg4:number):Promise<market.SearchResultServers>;

export function SearchMarketSkills(arg1:string,arg2:number,arg3:number,arg4:string):Promise<market.SearchResultSkills>;

export function SetTheme(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleAgent(arg1:string,arg2:boolean):Promise<void>;

export function ToggleMcpServerAgent(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ToggleSkillAgent(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UninstallSkill(arg1:string):Promise<skills.UninstallResult>;

export function UpdateMcpServer(arg1:string,arg2:mcp.Server,arg3:Array<string>):Promise<void>;

export function UpdateSettings(arg1:config.Settings):Promise<void>;

export function UpdateSkillRepo(arg1:config.SkillRepo,arg2:config.SkillRepo):Promise<void>;
